apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.issuerName }}
spec:
  ca:
    secretName: ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCrt }}
  tls.key: {{ .Values.tlsKey }}
