apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certName }}
spec:
  secretName: {{ .Values.secretName }}
  dnsNames:
  -  {{ .Values.dnsName }}
  issuerRef:
    name: {{ .Values.issuerName }}
    kind: ClusterIssuer
    group: cert-manager.io
