name: Deploy Ingress

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          release: nginx
          namespace: ingress-test
          chart: ingress
          token: ${{ github.token }}
          helm: helm3
          values: |
            dnsName: ${{ secrets.dnsName }}
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
