name: Deploy cluster-issuer

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          release: ca-issuer
          namespace: clusterissuer
          chart: clusterissuer
          token: ${{ github.token }}
          helm: helm3
          values: |
            tlsCrt: ${{ secrets.issuer_tls_crt }}
            tlsKey: ${{ secrets.issuer_tls_key }}
            caCrt: ${{ secrets.issuer_ca_crt }}
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
