name: Deploy Secret

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        uses: deliverybot/helm@v1
        with:
          release: mysecret
          namespace: secret-test
          chart: secret
          token: ${{ github.token }}
          values: |
            key: ${{ secrets.key }}
            crt: ${{ secrets.crt }}
        env:
          KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}
